name: Code Review

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t auto-code-review .

      - name: Test internet access
        run: docker run --rm -it auto-code-review ping -c 4 google.com

      - name: Run Docker container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REVIEW_PROMPT: ${{ secrets.REVIEW_PROMPT }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        run: |
          docker run -e OPENAI_API_KEY -e REVIEW_PROMPT -e LOG_LEVEL auto-code-review