name: Code Review

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t auto-code-review .

      - name: Run Docker container
        run: |
          docker run --env-file .env auto-code-review